display:
  cycle: false 
  inverted: true 
  orientation: 90
ticker:
  currency: bitcoin,ethereum,litecoin,monero
  exchange: default
  fiatcurrency: usd,eur,gbp
  sparklinedays: 28
  updatefrequency: 120
