display:
  cycle: false
  inverted: false
  orientation: 90
ticker:
  currency: bitcoin,ethereum,litecoin,bitcoin
  exchange: default
  fiatcurrency: gbp,usd,eur
  sparklinedays: 28
  updatefrequency: 300
